alertmanager:
  enabled: false
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.long-bui.de
      - grafana.monomo.network
    tls:
      - secretName: grafana-monitoring-tls
        hosts:
          - grafana.long-bui.de
          - grafana.monomo.network
  persistence:
    enabled: true
    storageClassName: hcloud-volumes
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: hcloud-volumes
kubelet:
  serviceMonitor:
    https: true
coreDns:
  enabled: true
  service:
    selector:
      k8s-app: kube-dns
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false