alertmanager:
  enabled: false
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
      certmanager.k8s.io/acme-challenge-type: http01
    hosts:
      - grafana.long-bui.de
    tls:
      - secretName: grafana-monitoring-tls
        hosts:
          - grafana.long-bui.de
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  rbac:
    roleNamespaces:
      - "kube-system"
      - "monitoring"
      - "default"
      - "kube-public"
      - "brick"
      - "long"
kubelet:
  serviceMonitor:
    https: true