version: '3.2'

services:
  nginx-webserver:
    image: nginx:latest
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./site-content:/usr/share/nginx/html
    labels:
      traefik.enable: 'true'
      # Adjust this!
      traefik.frontend.rule: 'Host:subdomain.domain.tld'
      traefik.port: '80'
      traefik.docker.network: 'backends'
    networks:
      - backends

networks:
  backends:
    external:
      name: reverse_proxy_backends
