ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  paths:
    - /
  hosts:
    - minio.long-bui.de
  tls:
    - secretName: minio-tls
      hosts:
        - minio.long-bui.de
persistence:
  size: 10Gi
resources:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 500m
metrics:
  serviceMonitor:
    enabled: true