version: '3.2'

services:
  traefik:
    image: traefik
    ports:
      # only expose https to outside world
      - '443:443' # SSL
    expose:
      # traefik dashboard port
      - 8080
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:traefik.long-bui.de'
      traefik.frontend.auth.basic.usersFile: ./.htaccess
      traefik.port: '8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
    restart: 'always'
    networks:
      - backends

networks:
  backends:
    driver: bridge
