version: '3.2'

services:
  traefik:
    image: traefik
    ports:
      - '80:80'
      - '443:443'
    expose:
      # traefik dashboard port
      - 8080
      # acme challenge
      - 80
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:traefik.long-bui.de'
      traefik.frontend.auth.basic.usersFile: '.htaccess'
      traefik.port: '8080'
    volumes:
      - ./.htaccess:/.htaccess
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
    restart: 'always'
    networks:
      - backends

networks:
  backends:
    driver: bridge
