rbac:
  create: true
controller:
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/name: 'ingress-lb'
defaultBackend:
  enabled: true